### ISSUE TITLE
Property.check' could throw a System.Exception,

### ISSUE THREAD

**Issue by moodmosaic** [jystic/dotnet-jack#34]
instead of returning `bool` and printing to stdout, because otherwise xUnit.net (and I believe also NUnit and MSTest) can't figure out whether a property fails or not:

```f#
[<Fact>]
let ``the reverse of the reverse of a list is the list itself`` () =
    Property.check <| property {
        let! xs = Gen.list Gen.int
        return List.rev xs = xs // Fails, on purpose.
    }
```
Output:

```
------ Test started: Assembly: Jack.Tests.dll ------

1 passed, 0 failed, 0 skipped, took 0.69 seconds (xUnit.net 2.1.0 build 3179).
```

Expected output:

```
------ Test started: Assembly: Jack.Tests.dll ------

Test 'Jack.Tests.ShrinkTests.the reverse of the reverse of a list is the list itself' 
failed: System.Exception : *** Failed! Falsifiable (after 5 tests and 3 shrinks):
[1; 0]

	at Microsoft.FSharp.Core.Operators.FailWith[T](String message)
	..\Property.fs(215,0): at Jack.PropertyModule.check'(Int32 n, Property`1 p)
	..\Property.fs(218,0): at Jack.PropertyModule.check(Property`1 p)
	..\PropertyTests.fs(126,0):
		at Jack.Tests.ShrinkTests.the reverse of the reverse of a list is the list itself()

0 passed, 1 failed, 0 skipped, took 2.86 seconds (xUnit.net 2.1.0 build 3179).
```

That, or we could add another function in the `Property` module that throws a System.Exception instead. – Let me know and I'd happily send a pull request :smiley:

**Comment by jystic** [comment]
This is fixed by https://github.com/jystic/dotnet-jack/pull/35

**Comment by moodmosaic** [comment]
Awesome! I'll check #35 in the next couple of hours, hopefully.
